### ISSUE TITLE
Import Txt File With AlaSql

### ISSUE THREAD

**Issue by akbalburak** [agershun/alasql#1035]
Hi, i am trying to import a txt file into a grid. everything is okay but there is a problem. When i am trying to import a txt file which has big numeric values like below, it doesnt import the correct data.

228050282620001145

This is what i am trying to import but below is what i got.

228050282620001140

Here is also what i am using.

alasql("SELECT * FROM FILE(?,{headers:false})", [event], function (data) {
// Do jobs
}

I am waiting for your helps. Thank you :)

**Comment by mathiasrw** [comment]
Numbers handled in javascript are 64-bit floating point values. The largest exact integral value is (2^535)-1, or 9007199254740991 - so the integer 228050282620001145 is simpley too big to be represented natively in javascript. 

If you have access to the source you could encapsulate the numbers witn `"..."` so its a string instead of a number.
