### ISSUE TITLE
Numbers not quoted in CSV

### ISSUE THREAD

**Issue by LukaszWiktor** [agershun/alasql#1049]
I'm trying to export data through AlaSQL to a CSV file:

```
var data = [
    {city: "Cracow", population: 754000}, 
    {city: "Warsaw", population: 1735000}
];

window.exportData = function exportData() {
    alasql("SELECT city, population INTO CSV('cities.csv') FROM ?",[data]);
}
```

The problem is that numbers get exported without quotes. Is it by design? Is there any way to get them quoted? I've tried `CAST(population as TEXT) as population` but the numbers are still not quoted

```
"city";"population"
"Cracow";754000
"Warsaw";1735000
```

http://jsfiddle.net/LukaszWiktor/kp9ybj35/

**Comment by mathiasrw** [comment]
Yes, this is by design and follows the [RFC](https://tools.ietf.org/html/rfc4180) for CSV files.

If you want to have it quoted you must loop your data and do something like `population = ''.population`

It might even work with a `alasql("SELECT city, CONCAT(population) INTO CSV('cities.csv') FROM ?",[data]);`but not 100% on the last one. 
`
