### ISSUE TITLE
Repo filestructure cleanup ideas

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#106]
Ideas to make the repo better 

- Make sure there are only one version of alasql.js - in the moment there is one in dist and one in root. 
- Change test and example scripts to always includ the one in dist so there is never an nonupdated version somewhere. 
- Make sure there is a building script that generates both alasql, the worker version (the console version?), and the cordova, version at the same time - so they all reflect the same compilation from src.
- Make sure there are no .js files in root (except the gulpfile) - its not clear if the files are an example, some testing things or just random stuff used at some point. Find out what it is, put it into a folder and name it well.
- Have one folder in root called test. Inside this test folder distribute the content of the exsisting test folder into testsql/sqllogic and test-sql (find out if you feel like keeping test-sql in the repo or you do not feel sure about the rights to use it. If not, remove it. If yes, remove it from gitignore)
- Put the worker files in dist into a folder called "worker" 
- Put the cordova files into dist in a folder called "cordova"

Questions
- is the /master/console folder a test of the worker? The files looks like example data - if so put it into test (or examples)
- I see the idea of /docs/sql but would it be more suitable to use a github wiki for that?
- What is the logic behind the /lib files? is it for test? for development? for the examples?

**Comment by agershun** [comment]
Great! Thank you for structuring ideas. Now it is a good time to clean file system. Hope it wont take to much time. I will write more detailed answer tonight.

One problem: why I need to keep alasql.js file in root catalog: the problem with gulp map plugin . I can make it work only properly when it is in root directory, because it generates wrong paths. Probably, the problem with setup in gulpfile.js.

**Comment by gregaubert** [comment]
:+1: for restructuring the repo

**Comment by mathiasrw** [comment]
Any news on this one?

**Comment by agershun** [comment]
Mathias, thank you for the patience:

**1. Make sure there are only one version of alasql.js - in the moment there is one in dist and one in root.**

Now, the alasql.js and alasql.js are the same by default. All other files removed from root directory to ```dist``` directory. I redesigned ```gulpfile,js``` to save results immediately to ```dist``` directory.

Unfortunately, due the problem with sourcemap files, I still cannot remove ```alasql.js``` and ```alasql.js.map```from the root directory.

**Change test and example scripts to always includ the one in dist so there is never an nonupdated version somewhere.**

All tests replaced to
```js
    var alasql = require('..');
```
which refers to alasql package itself.

**3. Make sure there is a building script that generates both alasql, the worker version (the console version?), and the cordova, version at the same time - so they all reflect the same compilation from src.**

* I changed gulpfile.js, now it send all result files to dist.
* Hope we do not need separate Cordova version

**Make sure there are no .js files in root (except the gulpfile) - its not clear if the files are an example, some testing things or just random stuff used at some point. Find out what it is, put it into a folder and name it well.**

I cleaned *.js in root directory, but I had to leave the following files:

* alasql.js - due the sourcemap problem
* alaserver.js - server utility. Probably we need to move it to separate directory
* alacon.js - console utility. 

** 4. Have one folder in root called test. Inside this test folder distribute the content of the exsisting test folder into testsql/sqllogic and test-sql (find out if you feel like keeping test-sql in the repo or you do not feel sure about the rights to use it.**

Not yet done. I will clean ```test``` directory later.

 If not, remove it. If yes, remove it from gitignore)

I removed all things from gitignore. Now there are no hidden things. Probably, we need to remove some of demo databases because of copyright issues. To be checked.

**5. Put the worker files in dist into a folder called "worker"**

Should be discussed. Are other libraries structure their worker versions on the same way? Now I move it to dist directory.

**6. Put the cordova files into dist in a folder called "cordova"**

I removed this directory, because the support of Cordova implemented inside current version of Alasql.

**Questions**

**7.is the /master/console folder a test of the worker? The files looks like example data - if so put it into test (or examples)**

This directory isa copy of ```http://alasql.org/console``` directory. I used it to minimize time to update demodata on alasql.org

**8. I see the idea of /docs/sql but would it be more suitable to use a github wiki for that?**

I will move all documentation to wiki and will clean this folder.

**9. What is the logic behind the /lib files? is it for test? for development? for the examples?**

I used these external library files for examples and tests.

**Comment by mathiasrw** [comment]
Booooommm - good job !

Let me know if I can help out with something...

**Comment by agershun** [comment]
Moved ```alacon.js``` and ```alaserver.js``` to ```bin/``` directory to make them runnable from the command line.

**Comment by gregaubert** [comment]
Just a question, is there any good reason for having all the node_modules used in the git repo ?
If not, I think it would be better to not track them on git and just add the `dependencies / devDependencies` in the `package.json` file.
What do you think ?

**Comment by mathiasrw** [comment]
:+1: for putting node_modules in .gitignore (and removing from repo)

**Comment by agershun** [comment]
Please, check me:

1. I will add these lines into ```package.json```:
```json
    {  
       "devDependencies": {
        "dom-storage":"2.0.1",
        "gulp":"3.8.11",
        "gulp-changed":"1.2.1",
        "gulp-concat-sourcemap":"1.3.1",
        "gulp-shell":"0.4.1",
        "jison":"0.4.15",
        "lodash":"3.7.0",
        "xlsjs":"0.7.15",
        "xlsx":"0.8.0"    
       },
    }
```

2. I will add these lines into ```.gitignore```
```
    node_modules/*
```

Everything is correct? If so, I will push these changes tonight

**Comment by gregaubert** [comment]
For the gulp stuff and jison you can put them in `devDependencies` for sure. But for the rest I don't know where you use it, perhaps it needs to be in `dependencies` instead ? Or you just use them in tests and stuff like that ?
I also noticed there is actually `redis` and `es6-promise` in your node modules.

**Comment by agershun** [comment]
```redis``` was included for future plans to support key-value database backend storages. Probably for version 0.2, so now it is not important.
