### ISSUE TITLE
Question about 'IN' operation

### ISSUE THREAD

**Issue by Eflet** [agershun/alasql#1072]
Hi,
for example, following code:
```
var datas = [...]   // about 10,000 items
var ids = [...] // about 700 items
var id2 = ids.map(id => "'" + id + "'").join(',')
// test1
alasql('select * from ? where id in ('+id2+')', [datas])
// test2
alasql('select * from ? where id in @(?)', [datas, ids])
```
test2 is about 3 times faster than test1, 
then I search the source code ,  from alasql/src/50expression.js , I think test 1 will execute line 524 and test2 will execute line 521.
So what's the difference ? Is that all use `.indexOf`?

**Comment by agershun** [comment]
The time difference can be explained with the parser, because it is relatively slow.
In the first case there is additional work for parser to parse the source code with an array.
In the second test AlaSQL does not parse data from `ids` array.

**Comment by Eflet** [comment]
> The time difference can be explained with the parser, because it is relatively slow.
> In the first case there is additional work for parser to parse the source code with an array.
> In the second test AlaSQL does not parse data from `ids` array.

I don't think it will take more time to parse the sql, since in the second case it will flatten the array use map function (line 521 in 50expression.js), 

I think it's caused by the difference between String.indexOf and Array.indexOf.
It seems Array.indexOf is far more fast than string.

I try to change the line 524 like this:
`s = '([' + rightJS() + '.indexOf(' + leftJS() + '])>-1)';`
 the two test case spend almost same time to finish.

**Comment by mathiasrw** [comment]
Hi @Eflet - Thank you so much for looking into this. 

Unfortunatly the change to `s = '([' + rightJS() + '.indexOf(' + leftJS() + '])>-1)';` [did not compile](https://travis-ci.org/agershun/alasql/jobs/452807507#L678) as valid JS. 

I looked a bit into it and realised you might placed the `]` wrong in your message and tested `s = '([' + rightJS() + '].indexOf(' + leftJS() + ')>-1)';`. Unfortunatly this did not work because it generated code like `([y[0]].indexOf(y[1])>-1)`.

Any inputs to what the edit could have been?

**Comment by Eflet** [comment]
OK, sorry I made a mistake. Actually test case 1 will execute the line 521.   My changes on source code is totally wrong.
So I agree with agershun that the time cost is from parser.

Thanks a lot, alasql is good!
