### ISSUE TITLE
Alasql Release 0.1.0 - list of urgent bugs

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#111]
Dear friends,

I going to release Alasql version 0.1. Please, can you post here what urgent bugs should be fixed before this release will be published:

My wish list:
* Clean the directory structure - **UPDATE work in progress**
* Fix localStorage bugs (DELETE FROM) - **UPDATE now fixed**
* Fix INDEX bugs (Something wrong with index...) - **UPDATE - now fixed**
* UNION bug - **UPDATE** - fixed!

What else is urgent?

Sorry, for slow work on some bugs - unfortunately (or fortunately:) I am very busy on my main project. 

Thank you!

**Comment by mathiasrw** [comment]
Urgent is to update wiki / documentation with what is not supported... Then people have a chance to read it before they put too much work into alasql before finding out that little part is missing...

**Comment by agershun** [comment]
:+1:  I can work on wiki documentation on the second part of April.

**Comment by pdiniz13** [comment]
Hey:

I'm currently a student at Hack Reactor and me and a group of three other students are currently working on out thesis project which will be adding PostgreSQL support to meteor.  We have most of the back worked out and are about to start working on the front end and adding a minisql support to meteor and connecting it to postgres' notify functionality to maintain the real time data updates. I was originally going to use IndexedDB until I came across your library and we're considering using your library instead. Would you have the time for a quick 30 min video chat to walk me through the current major bugs so that we can either try to fix them or work around them? We would of course be sending out pull requests for any issues that we ended up solving.

regards,

Paulo

**Comment by agershun** [comment]
HI, Paulo, thank you! Can you write on my email agershun@gmail.com and we can define a time of the video chat.

**Comment by vchigne** [comment]
@pdiniz13 Great project. Do you have any ETA?

**Comment by pdiniz13** [comment]
@vchigne thank you for your interest. We currently have a prototype with full stack interactivity in Meteor using both Postgres and Alasql. We are currently refactoring a couple of parts of our code in order to make it more modular and easy to use, and improving our documentation. We should be releasing a beta package for meteor in about two weeks.

**Comment by vchigne** [comment]
Great. I can beta test if you want.

Let me know

**Comment by agershun** [comment]
Guys, sorry, what is "ETA"?

**Comment by vchigne** [comment]
Estimated Time of Arrival IIRC

**Comment by agershun** [comment]
Target day for version 0.1 is May 1, 2015.

I also want to add:
*  Bower support 
* and spend more attention to SQL compatibility tests.

**Comment by mathiasrw** [comment]
>  spend more attention to SQL compatibility tests

Ill see what I can do to get my scripts matured and merged into a feature branch.

**Comment by agershun** [comment]
Can you add two features to the test:
a) total result, i.e. AlaSQL passed 35% - we will use it as our KPI
b) to show failed tests body (to make debugging easy)

**Comment by agershun** [comment]
I also worried a little bit about size of sqllogic tests. Now they are about 100Mb. May be we can open separate repository for all tests?

**Comment by mathiasrw** [comment]
Its more like 1,5 Gb when you unzip it...

I have created a repo focused on the sqllogic tests: https://github.com/mathiasrw/alasql-logictest

I have added you to the repo. 

Its ready to run some tests  - check README

**Comment by agershun** [comment]
Wonderful!  This will be a great step for the project!

I will try to run tests tonight and give a feedback.
I also have collected number of test SQL databases in ```test-sql``` directory to additional compatibility tests.

**Comment by agershun** [comment]
About versions: I going to upgrade minor version to 0.1.0 after fixing UNION CORRESPONDING bug. Hope, it will happen very soon :)

**Comment by mathiasrw** [comment]
Sounds great :)

**Comment by agershun** [comment]
So, battle for UNION CORRESPONDING/non-CORRESPONDING is over!

Probably, only two bugs delays us from 0.1:
* IE9 FileSaver issue (https://github.com/agershun/alasql/issues/73)
* localStorage problem (https://github.com/agershun/alasql/issues/144)

**Comment by agershun** [comment]
I fixed IE9 (partially). Unfortunately, cannot reproduce localStorage and INNER JOIN problem. We will work on it as long as with sqllogic tests.

So,... as we decided before we released the version 0.1.0 (ta-ta-da!)

**Comment by mathiasrw** [comment]
Sorry I did not respond to your request to test it. Had to focus on other things. Just trying to catch up on the last 24 days of development :)

**Comment by agershun** [comment]
@mathiasrw Thank you for coming back. t was terrible time without advices and support :)

**Comment by mathiasrw** [comment]
![You are the best](http://hglogisticsllc.com/wp-content/uploads/2013/05/Express-Appreciation.png)
