### ISSUE TITLE
Query returning incorrect result

### ISSUE THREAD

**Issue by an0sv** [agershun/alasql#1129]
I expected that this query would result in 0 rows, at least it does in postgres and others.

alasql("select l, count(*) as rc from ? where l='c' group by location", [[{"l":"a"},{"l":"b"}]]);

But it returns the result:

[{l: undefined, rc: 0}]

**Comment by mathiasrw** [comment]
Oh - this is really interesting. Thank you for taking time to condense it. 

If you select a `count` you will always get one row out with the number of the counted items. 

`l is undefined` because no row was selected. If you had more than one row selected there is _no_ way to tell from what row the l value came from - how  ever - this is not a problem as you selected on l (and actually already know the answer).
