### ISSUE TITLE
Could be useful in Cloudflare Workers

### ISSUE THREAD

**Issue by tmikaeld** [agershun/alasql#1218]
I tried it on a worker, but workers don't allow function generators.

Is there any way to work around the function generation?

**Comment by mathiasrw** [comment]
There is no way alasql can run without being able to make a function. The whole idea is that the execution is made as a function so that its as fast as possible. 

There have been some ideas into precompiling functions during a build step (just like running alasql.compile('xxx') and then saving the dynamic functiona as a static function)

In theory you would be able to do that manually - but it is not a pretty task...

**Comment by tmikaeld** [comment]
@mathiasrw 

Makes sense, thanks for the reply, really appreciate it.
