### ISSUE TITLE
How to get column list from excel ? 

### ISSUE THREAD

**Issue by btomashvili** [agershun/alasql#148]
I want to get headers row  from exel as column list , is any ready solution for this issue ?

```
alasql('select * from xlsx("/uploads/cities.xlsx",{headers:true})',
        [],function(data){
   console.log(data);
        });
```

**Comment by btomashvili** [comment]
So id did it but  i dont like this solution 

```
  var obj =  data[0];
  console.log(Object.keys(obj));
```

**Comment by agershun** [comment]
I am currently working on this issue (this issue is related to many other issues here, including UNION problem). Hope, I can finish on May 5, 2015.

AaSQL will have a special option to return a recordset instead array, like:

    alasql.pptions.modifier = "RECORDSET";

 And after that alasql() function will return Recordset object with columns and data.

**Comment by agershun** [comment]
Could you download ```develop``` version of [alasql.min.js](https://raw.githubusercontent.com/agershun/alasql/develop/dist/alasql.min.js) and try this construction:
```
    var rs = alasql('SELECT RECORDSET * FROM XLSX("mydata.xlsx",{headers:true})');
```
or
```
    alasql.options.modifier = 'RECORDSET';
    var rs = alasql('SELECT * FROM XLSX("mydata.xlsx",{headers:true})');
```
AlaSQL will returns a Recordset object with two properties:
* data - the data
* columns - list of columns with field ```columnid```

In the future AlaSQL will also returns ```typeid``` field.
