### ISSUE TITLE
Check if xlsjs package is still necessary

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#171]
According https://github.com/SheetJS/js-xls:

<blockquote>
NOTE: this project has been merged into js-xlsx. The API is identical to js-xls. Some future changes may be backported, but all new projects should use js-xlsx.
</blockquote>

**TODO:** TO check, if these two pacakges are still necessary and to eliminate oldest one.

**Comment by mathiasrw** [comment]
Did you ever check up on this?

**Comment by reviewher** [comment]
@agershun @mathiasrw all of the js-xls logic has been folded into js-xlsx.  The browser script for js-xlsx actually exposes both XLS and XLSX variables so there's no need to require both scripts.

The simplest change would be to replace all instances of requiring `xlsjs` with `xlsx`, removing bower references to `js-xls`, and removing source references to `xls.js` and friends.

In the jump to 0.9 we also folded in the ODS support into the main xlsx source, so that comes for free too :)  The current read/write support is detailed in [a table in the README](https://github.com/SheetJS/js-xlsx#file-formats) and summarized in a diagram: ![formats.png](https://github.com/SheetJS/js-xlsx/raw/master/formats.png)

**Comment by mathiasrw** [comment]
This is really really awesome! Thanks for letting us know!
