### ISSUE TITLE
Issue with NOT grouping

### ISSUE THREAD

**Issue by workmad3** [agershun/alasql#386]
When writing a query with a NOT in the WHERE clause, the result seems to indicate that the precedence grouping in the query is incorrect, as it appears to group a `NOT` with just the column name not the full expression when not using parenthesis.

Reproducible with:
`alasql('SELECT a FROM ? WHERE NOT id = 2', [[{id:2,a:123},{id:1,a:null}]])`
(no results)
vs
`alasql('SELECT a FROM ? WHERE NOT (id = 2)', [[{id:2,a:123},{id:1,a:null}]])`
(1 result, as expected)

**Comment by agershun** [comment]
@workmad3 Thank you for the note. It is so, because we place NOT with higher priority than ```=```. 

I just checked SQL standards and some realizations (e.g. [Transact SQL](https://msdn.microsoft.com/en-us/library/ms190276.aspx), [MySQL](https://dev.mysql.com/doc/refman/5.0/en/operator-precedence.html). You are right, we need to fix it.

**Comment by mathiasrw** [comment]
Thank you for taking the time to investigate and describe the issue. 

@agershun Could this be the same cause as issue #368 ?

**Comment by agershun** [comment]
I fixed it. See the version in ```develop``` branch.

**Comment by workmad3** [comment]
@agershun Seems good in my initial testing, just going to ask some of my users to test the change as well. Thanks for the quick fix!

**Comment by workmad3** [comment]
My users just confirmed the fix works as expected too, and pass on their thanks!

Closing this issue.
