### ISSUE TITLE
Double quotation marks in CSV output

### ISSUE THREAD

**Issue by rusco** [agershun/alasql#431]
In this example (v 0.19) everything works fine:

http://jsfiddle.net/agershun/g855dn9b/

``` javascript
<script src="http://alasql.org/console/alasql.min.js"></script>

<button onclick="window.exportData()">Export data to CSV file</button>
var data = [["Minsk",100000], ["Riga",200000]];
window.exportData = function exportData() {
    alasql("SELECT * INTO CSV('cities.csv') FROM ?",[data]);
}
```

in this example (v 0.21) I get one more quotation mark than expected (Latest Chrome, Win7/64 OS):

http://jsfiddle.net/g855dn9b/30/

``` javascript
<script src="http://cdn.jsdelivr.net/alasql/latest/alasql.min.js"></script>

<button onclick="window.exportData()">Export data to CSV file</button>
var data = [["Minsk",100000], ["Riga",200000]];
window.exportData = function exportData() {
    alasql("SELECT * INTO CSV('cities.csv') FROM ?",[data]);
}
```

additional quotation mark at the beginning: 
""Minsk";100000
"Riga";200000

removing this line in function "alasql.into.CSV" makes the problem dissapear: 

``` javascript
    s = (s+"").replace(new RegExp('\\'+opt.quote,"g"),'""');
```

**Comment by mathiasrw** [comment]
Since 0.0.19 [we have changed](https://github.com/agershun/alasql/commit/a6e42f5b53608ee9972457a597bddb6a3c14ca33#diff-607f5f84acd3a4532cb59ce4755a198eR193) the way we export `.csv`  to worship the great Excel 2013 ignores the [`.csv` RFC standart](https://tools.ietf.org/html/rfc4180) 

Looks like the edit have introduced an error. 

Im not really sure why it would produce an extra `"` in the Minsk line, but not the Riga line. 

Ill expriment a bit. 

I all cases: `s = (s+"").replace(new RegExp('\\'+opt.quote,"g"),'""');`  is there to make sure the content of a cell could be something like `You "real" name` - so its not good to remove it is not a solution...

**Comment by mathiasrw** [comment]
Got it - was a part that was not removed when introducing the change as mention in prev. comment.

Check out http://jsfiddle.net/g855dn9b/31/

While we are preparing a new release please use the file at 

https://cdn.rawgit.com/agershun/alasql/f4a38bf4f1e16969030612f3bc13a2a5c40789af/dist/alasql.min.js

**Comment by rusco** [comment]
:clap:

**Comment by junedansari** [comment]
again getting same issue on latest version ie. 0.3.4

**Comment by mathiasrw** [comment]
Terrible - can you provide some code that generates the problem?

**Comment by mathiasrw** [comment]
CLosing - continueing in the new issue
