### ISSUE TITLE
Exported xls file shows warning in Microsoft Excel

### ISSUE THREAD

**Issue by harikrishnanp** [agershun/alasql#442]
When I open the exported xls file in Microsoft Excel it shows this warning "Excel found unreadable content in *******.xls. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click yes" . If I click yes , it shows the content correctly. But the warning is  really annoying for users. Please resolve.

**Comment by mathiasrw** [comment]
Interesting. 

Would it be possible for you to provide an example generateing a file that gives this alert?

**Comment by harikrishnanp** [comment]
Yes. I can. Please hold on.

**Comment by harikrishnanp** [comment]
I have emailed you the document. I'm getting this error "Attaching documents requires write permission to this repository" when I tried to attach.

**Comment by mathiasrw** [comment]
Its best if you put put the code to generate the problem file here on github.

**Comment by mathiasrw** [comment]
@harikrishnanp 

Hvae you had time to look at what code generates the problem files?

**Comment by harikrishnanp** [comment]
Please find the sample code that will generate the above error.
`var data = [{city:"Minsk",population:100000}, {city:"Riga",population:200000}];

window.exportData = function () {
        alasql("SELECT * INTO XLSX('cities.xlsx',{headers:true}) FROM ? ",[data]);
    }`

**Comment by mathiasrw** [comment]
Great thanks !


update: wow - even a JSFIDDLE - perfect - thanks...

**Comment by mathiasrw** [comment]
You are using an old version of AlaSQL

Please use https://cdnjs.cloudflare.com/ajax/libs/alasql/0.2/alasql.min.js as in this (JSFIDDLE)[http://jsfiddle.net/0xgfjcre/46/]

**Comment by harikrishnanp** [comment]
https://cdnjs.cloudflare.com/ajax/libs/alasql/0.2/alasql.min.js  is 404

**Comment by harikrishnanp** [comment]
It's https://cdn.jsdelivr.net/alasql/0.2.1/alasql.min.js

**Comment by mathiasrw** [comment]
Sorry for that - I posted wrongly first - hoped I had time to correct it before you saw it :)

**Comment by rupendras-optimus** [comment]
Did it solved the issue? I am using the suggested version but still getting the same warning message while trying to open the exported excel?

**Comment by mathiasrw** [comment]
We have not found a solution yet.

**Comment by kingsbury** [comment]
@mathiasrw your last [fiddle](http://jsfiddle.net/0xgfjcre/51/) worked fine for me in Chrome, no alert generated in Excel 2010.

**Comment by mathiasrw** [comment]
Oh... thanks @kingsbury - I might got confused about the issues

@rupendra-sharma07 could you try http://jsfiddle.net/0xgfjcre/51/ and see if you get an error in excel? It should work...

**Comment by harikrishnanp** [comment]
My issue was fixed by updating AlaSQL.

**Comment by RAFBOUK** [comment]
Hello every body, i have the same problem when i try to open the export  ==> 
alasql( 'SELECT * INTO XLS("' + exportFileName + '.xls",?) FROM ?',[ opts, data] );
and when i use this second request alasql( 'SELECT * INTO XLSX("' + exportFileName + '.xlsx",?) FROM ?',[ opts, data] ); i don't have the warning but i can't include styles inside xlsx file, i think it's normal because in the alasql's documentation they use the request without any "opts" just like this (alasql( 'SELECT * INTO XLSX("' + exportFileName + '.xlsx",?) FROM ?',[data] );),
My question is : how can i export excel file from json with ALASQL without the warning when i try to open it and i can include some styles inside the file ? thx in advance for your responses

**Comment by mathiasrw** [comment]
@RAFBOUK Please open 2 new issues with one question in each

**Comment by juni103** [comment]
I have the same issue as @RAFBOUK . did anyone found solution?

**Comment by mathiasrw** [comment]
@juni103 Please open a new issue on this.

**Comment by starrybleu** [comment]
For future readers,
I also met this issue. But the problem was my null value which would be cell value.

For example, 

`const data = [{city:"Minsk",population:100000}, {city:"Riga",population:200000}];` will be fine.

However,

`const data = [{city:"Minsk",population:100000}, {city:"Riga",population: null}];` will cause this problem again.

Additionally, `undefined` is ok.

**Comment by clough1** [comment]
Hello @mathiasrw.  I have to upgrade the alasql/xlsx versions. I am now on the latest version of alasql (0.4.11) and xlxs (0.7.12). When I download and open the excel file I get the error: 

> We found a problem with some content in 'test_data.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

I do have some rows of data with "null". This wasn't an issue in my previous alasql version 0.4.0. Is there a solution for this?

**Comment by mathiasrw** [comment]
We have not found a way to solve this. Its because we are not Microsoft and its warning that some other party (you) made the file. 

If you just click "yes" its all gonna work.

**Comment by pedrozan** [comment]
Hi @mathiasrw. Is there any news about this problem?

**Comment by mathiasrw** [comment]
Nope.
