### ISSUE TITLE
Bleeding Edge in cdn

### ISSUE THREAD

**Issue by nbdamian** [agershun/alasql#632]
Would it be possible to have the bleeding edge version in a CDN.

Often what I am testing, it will be in jsfiddle or similar, and they don't allow external resources from github.

**Comment by mathiasrw** [comment]
I would love that. If you have any inputs on how to get it stored somewhere smart on push please let me know and Ill fix it. 

Weill... At the moment we have a rawgit develop-testing-cdn for the bleeding edge version, but we dont want to advertise it so people dont start to use it in because the CDN limits the amount of accesses (and then will break the sites using it) 

Using the jsfiddle http://jsfiddle.net/vahrxxzm you will always will always include the bleeding edge version: https://rawgit.com/agershun/alasql/develop/dist/alasql.js
