### ISSUE TITLE
xlsx.js 0.8 does not work with AlaSQL

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#678]
_From: https://github.com/agershun/alasql/issues/650#issuecomment-219303137_

> I had the exact same issue as angelok1. I've figured out that using xlsx.js version 0.7.12 instead of 0.8 as what alasql 0.2.6 is requesting as requirement worked for me importing xlsx files. Btw. I am using angular in my code but isolated a test using just alasql.js 0.2.6 and xlsx.js 0.8 and it was giving the same problem. Changing to xlsx.js 0.7.12 fixed the issue. One issue though is bower doesnt pick up version 0.7.12 I had to get it from here https://cdnjs.com/libraries/xlsx/0.7.12

We must find out what has changed in the API

**Comment by nbdamian** [comment]
We should go through the github commits of xlsx.js and find what changes might have caused this issue.

**Comment by nbdamian** [comment]
I was looking at their repo, and I don't think they even have a tag for 1.7.12...

**Comment by mathiasrw** [comment]
0.7.12 is located at https://github.com/SheetJS/js-xlsx/tree/f9097d403b44a0165ecb45dd9a798492b462b339

**Comment by nowzig** [comment]
I inserted before this [line](https://github.com/agershun/alasql/blob/75c867174df9cdf33d85866f93f6ee68158e46bc/src/84from.js#L353) this code 
`var data = new Uint8Array(data);
var arr = new Array();
for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
data = arr.join("");` 
and then the error is gone. Very helpful was the second code example in [xlsx](https://github.com/SheetJS/js-xlsx#parsing-workbooks)

**Comment by mathiasrw** [comment]
@nowzig  

Thank you!

**Comment by mathiasrw** [comment]
Hmm... something is wrong. Had to remove the commit. 

I get 

> Uncaught Error: Unsupported file NaN
>      at Object.readSync [as read] (/home/mathiasrw/git/alasql/node_modules/xlsx/xlsx.js:11397:18)

**Comment by nowzig** [comment]
hm, strange, in my browserify environment it is working. I tested in Chrome and in Firefox. All the xls and xlsx files, I have, are read perfectly...

**Comment by mathiasrw** [comment]
Im running the test on node... hmmm. Interesting...

**Comment by mecorusfc** [comment]
Is there any hope of this getting fixed?  Right now, in order to make it work, I have to have this in my bower.json:

    "js-xlsx": "https://cdnjs.com/libraries/xlsx/0.7.12",
    "alasql": "0.2.3"

That's too far back to rely on.  It looks like nobody is assigned to it.  Is it possible to retry that commit that was later removed but only have that code active for FILE so that it is used for browser based usage?  Should we be looking at alternatives to alasql for importing Excel files?

**Comment by mecorusfc** [comment]
After looking at the source and comparing the 15utility.js file between 0.2.3 and 0.2.4 (first broken version), I see that nowzig's code above was actually in 15utility.js starting at line 355 in 0.2.3 exactly like the code above (which comes from a js-xlsx example).  In 0.2.4 some additional code was added to the 15utility.js file so this block was moved down further but most importantly, this critical fix to make browser loading of Excel work WAS REMOVED in 0.2.4.  If you look at 0.2.3 at line 349, you'll see the block that starts with: 

if(typeof path === "string") {

That block in 0.2.4 is now moved down to line 362.  That needed code would likely have been after line 390 if the onload had stayed around and not been removed.

I see one more issue that is a concern.  The call to the cutbom method is included both in that block at line 380 and also at the next block at line 411.  I'm not sure that is needed in all cases.  It seems like the obvious fix is to go back to the code in version 0.2.3.  I'll take a look at later versions to see how much the 15utility.js file has changed since then.

**Comment by mecorusfc** [comment]
Looking at version 0.3.7, the 15utility.js file still has those blocks although they have moved further down in the file.  The loadfile function is now at line 294 and the block where the code was removed starts at line 384.  Perhaps the missing code could be added back in the onreadystatechange in the success block before calling the success callback.  

Also, my upload is failing using Event so it would be the next block.  I strongly suspect that taking out the cutbom call would fix it for me (remove cutbom call from line 433 so the code looks exactly like version 0.2.3).

**Comment by mecorusfc** [comment]
Ohhhh, I see now - there are two major blocks (one for text and the other for binary) that look a lot like each other.  I got misaligned on the 0.2.4 release and was looking at the text block by accident.

**Comment by mecorusfc** [comment]
Sorry about my confusion above about the 15utility.js file.  I was looking in the wrong block when comparing between 0.2.3 and 0.2.4.  The blocks for loading text and binary files have the same structure so it is easy to get them confused.  However, I'm still trying to figure out what busted in 0.2.4 and has stayed busted since then.  I continued to look at 15utility.js.  I found an issue with this title:

Fix: IE11: Reading Excel File

Issue #397. The change was in the area that handles the Event type of upload.

reader.readAsBinaryString(files[0]);

was changed to...

reader.readAsArrayBuffer(files[0]);

While the description talked about fixing IE11, I didn't see any if statement around it to verify that this code change would only happen when IE11 was used.  Since it seems to break other browsers, I'd suggest the possibility of adding some kind of if statement to only make that change for IE11.  I'm going to find a machine with IE11 to see if my failing code will work with an up-to-date version of alasql.  Note that it works for me on Chrome on 0.2.3 with later versions of js-xlsx so the version of js-xlsx doesn't seem to be an issue as I thought it was before, based on reading above in the thread.  I'll report back with more information on whether it works in IE11 but not in Chrome or other browsers.

**Comment by mathiasrw** [comment]
Would you be able to test if the problem is still there in 3.8? I just released it with #835 merged and [the  changes](https://github.com/agershun/alasql/pull/835/commits/7392305cc1f334c0d102fb4fd4816950f353e2cb) might have solved this one too.

Also, xlsx lib is now latest version (0.9.2)

**Comment by mecorusfc** [comment]
Thanks for giving it a try.  When I changed the version in my bower.json to 0.3.8 and did a bower update, I got this error:

bower alasql#0.3.8                      ENORESTARGET No version found that was able to satisfy 0.3.8

Should I wait for some time to allow the version to propagate to all the right repos?

Thanks again, Mike

**Comment by mathiasrw** [comment]
Strange. Both bower and npm has version 0.3.8

https://libraries.io/bower/alasql
https://libraries.io/npm/alasql

Does bower cache the results?

**Comment by mecorusfc** [comment]
These libraries.io URLs give a 524 timeout error.  Is there a direct URL I can use to get to this version?

**Comment by mecorusfc** [comment]
I tried to go after 0.3.8 directly with a URL the way I was able to do with xlsx but I got a 403.  Apparently, there is authorization set up around alasql that isn't on xlsx.

    "alasql": "https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8"

bower alasql#*                                            EHTTP Status code of 403

**Comment by mecorusfc** [comment]
Our Nexus was caching something.  After invalidating the cache, I'm able to get 0.3.8 but it still depends on xlsx 0.8 instead of 0.9.2.  Here is the message from a bower update:

Unable to find a suitable version for js-xlsx, please choose one by typing one of the numbers below:
    1) js-xlsx#~0.8 which resolved to v0.8.8 and is required by alasql#0.3.8
    2) js-xlsx#0.9.2 which resolved to v0.9.2 and is required by <myapp>

I'll go ahead and force 0.9.2 to see if it works.

**Comment by mecorusfc** [comment]
I'm happy to report that version 0.3.8 works for my use case.  I'm importing an Excel file using the SELECT * FROM FILE with an event.

**Comment by mathiasrw** [comment]
Nice work everyone - thanks for all the bugreports, feedback, PRs, and testing!
