### ISSUE TITLE
Default csv separator is not comma.

### ISSUE THREAD

**Issue by chris-kbk** [agershun/alasql#775]
The default separator for csv type is not comma. It is semicolon on current version.

https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L14416

**Comment by mathiasrw** [comment]
Its correct that the default seperator is `;` and not `,` as specified by the [RFC](https://www.ietf.org/rfc/rfc4180.txt). The reason is that [Excel cant always handle ','](https://kb.paessler.com/en/topic/2293-i-have-trouble-opening-csv-files-with-microsoft-excel-is-there-a-quick-way-to-fix-this#reply-5193). As Excel usageis such a big usercase for the library we rather bother people who can't handel the incorrect `.csv` file with adding the parameter {seperator:','} than getting questions from all the people who cant make the lib "work" with Excel. 

I have update [the wiki](https://github.com/agershun/alasql/wiki/Csv) with this information
