### ISSUE TITLE
Wiki edits

### ISSUE THREAD

**Issue by morrme** [agershun/alasql#865]
I have made several edits to the wiki home page but I cannot do a pull request. Most of my edits are to correct the hyperlinks, as well as a typo. How can I get these to you?

**Comment by mathiasrw** [comment]
I know - the wiki cant be PR'ed

do a `git diff > mypatch.patch` and add drag the file into a comment field here at the issue and I will apply it to the wiki

**Comment by morrme** [comment]
Here it is in `.txt` format.....this system would not accept a `.patch` file.
[wikichanges.txt](https://github.com/agershun/alasql/files/949880/wikichanges.txt)

**Comment by mathiasrw** [comment]
Hmm. 

ok, one needs to do add a `--color=never` when saving the patch because the color info makes strange stuff to the input - and I have not been able to clean the file. 

So something like 

`git diff HEAD > fix.patch --color=never` 

shuold give the correct file - it can be checked by you doing a 

`git apply fix.patch --check`

If this does not work I read the diff manually and make the changes...

**Comment by morrme** [comment]
I have tried a few more times and all of the files look the same. Is there anything I can do to convert  the files to a format that works for you? 
[fix.txt](https://github.com/agershun/alasql/files/955448/fix.txt)

**Comment by mathiasrw** [comment]
Hey. sorry for not getting back to you. Ill make it work from her !
