### ISSUE TITLE
Example fiddles 

### ISSUE THREAD

**Issue by StuartGW** [agershun/alasql#885]
Hi.  I'm completely new to alasql and struggling to get started.
When I try the examples shown at https://github.com/agershun/alasql/wiki/Examples
e.g. Simple examples: sample 1, sample 2,
I just get a 404 error.  Should I have installed something first?

Specifically on sample 1:
Failed to load resource: the server responded with a status of 404 ()   -   alasql.min.js

Using Chrome 58

Rgds, Stuart

**Comment by mathiasrw** [comment]
thank you for taking the time to reaching out.

Its because the examples link to https://rawgit.com/agershun/alasql/master/alasql.min.js

rawgit is only ment for testing thinkgs, so they give a 404 when too many use the resource. 

I have replaced the links of the 2 first examples so they point to a jsfiddle that uses a "real" cdn... so everything should be good now :)

Please let me know if you find more examples that does not work...
